---
- name: Example of parameterized role and app startup
  vars_files:
    - 'vars.yml'
  hosts: a.b.com
  roles:
    - { role: 'retina', when: "'web' in group_names", app_name: 'retinaOne' }
    - { role: 'retina', when: "'data' in group_names", app_name: 'retinaTwo' }
    - { role: 'pupil', when: "'broker' in group_names", app_name: 'pupilOne' }
    - { role: 'pupil', when: "'broker' in group_names", app_name: 'pupilTwo' }
