---
- name: redeploy with notify restart
  shell: 'echo "we just redeployed {{app_name}}"'
  notify: restart {{app_name}}
  register: my_message

- name: just some feedback here
  debug: msg="{{my_message}}"

- debug: msg="{{app_name}} -- {{hip_apps[app_name].log_level}}"